# Generated by Django 5.2.7 on 2025-10-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_income"),
    ]

    operations = [
        migrations.RenameField(
            model_name="income",
            old_name="income",
            new_name="amount",
        ),
    ]
