# Generated by Django 5.2.7 on 2025-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="text",
            field=models.CharField(default="Token", max_length=260),
        ),
    ]
