# Generated by Django 5.2.7 on 2025-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_token_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="text",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
