# Generated by Django 5.2.7 on 2025-10-22 18:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_expense_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(verbose_name=django.contrib.auth.models.User),
                ),
                ("password", models.CharField(max_length=48)),
            ],
        ),
    ]
