# Generated by Django 5.2.7 on 2025-10-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_register"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Register",
        ),
    ]
